Type.find_or_create_by(title: 'Dev Notes')
Type.find_or_create_by(title: 'Addresses')
Type.find_or_create_by(title: 'VIM Notes')
Type.find_or_create_by(title: 'Markdown')
Type.find_or_create_by(title: 'Quote')